## Data Preprocessing

In [1]:
from datasets import load_dataset
from pandas import DataFrame as df

raw_datasets = load_dataset("conll2003")

Reusing dataset conll2003 (/root/.cache/huggingface/datasets/conll2003/conll2003/1.0.0/40e7cb6bcc374f7c349c83acd1e9352a4f09474eb691f64f364ee62eb65d0ca6)


  0%|          | 0/3 [00:00<?, ?it/s]

In [2]:
raw_datasets

DatasetDict({
    train: Dataset({
        features: ['id', 'tokens', 'pos_tags', 'chunk_tags', 'ner_tags'],
        num_rows: 14041
    })
    validation: Dataset({
        features: ['id', 'tokens', 'pos_tags', 'chunk_tags', 'ner_tags'],
        num_rows: 3250
    })
    test: Dataset({
        features: ['id', 'tokens', 'pos_tags', 'chunk_tags', 'ner_tags'],
        num_rows: 3453
    })
})

In [3]:
example_entry = raw_datasets["train"][4]

In [4]:
ner_feature = raw_datasets["train"].features["ner_tags"]
feature_names = ner_feature.feature.names

In [5]:
tokens = example_entry["tokens"]
tag_ids = example_entry["ner_tags"]
tags = map(lambda tag_id:feature_names[tag_id], tag_ids)

df(zip(tokens, tag_ids, tags))

0  1      2
0          Germany  5  B-LOC
1               's  0      O
2   representative  0      O
3               to  0      O
4              the  0      O
5         European  3  B-ORG
6            Union  4  I-ORG
7               's  0      O
8       veterinary  0      O
9        committee  0      O
10          Werner  1  B-PER
11       Zwingmann  2  I-PER
12            said  0      O
13              on  0      O
14       Wednesday  0      O
15       consumers  0      O
16          should  0      O
17             buy  0      O
18       sheepmeat  0      O
19            from  0      O
20       countries  0      O
21           other  0      O
22            than  0      O
23         Britain  5  B-LOC
24           until  0      O
25             the  0      O
26      scientific  0      O
27          advice  0      O
28             was  0      O
29         clearer  0      O
30               .  0      O

In [6]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

In [7]:
tokenizer.is_fast

True

In [8]:
inputs = tokenizer(tokens, is_split_into_words=True, truncation=True)
# inputs = tokenizer(tokens)
# df(inputs.tokens())

In [9]:
# inputs.word_ids()

In [10]:
# df(zip(inputs.tokens(), inputs.word_ids()))

In [11]:
from typing import List
def align_labels_with_split_tokens(labels_for_word_id: List[int], word_ids: List[int]) -> List[str]:
    """
    Given the map from id of each original word to the orignal label 
    and the word_ids list indicating how the tokenizer split each word, 
    return labels for the tokenized sentence, with word parts 
    padded as "inside".

    For example, if LAMB (B-ORG) is split into LA and ##MB,
    label LA as B-ORG and ##MB as I-ORG. 
    """
    output = []
    prev_word = None
    for word_id in word_ids:
        if word_id is None: 
            # [CLS] or [SEP]
            new_tag_id = -100

        else:
            original_tag_id = labels_for_word_id[word_id]
            if word_id != prev_word:
                # New word.
                # Use the exact same tag id.
                new_tag_id = original_tag_id
            
            else:
                # Non-leading part of a word that was split.
                # Flip any "B-" (odd label id) into "I-" (by adding 1.)
                if (original_tag_id % 2 == 1):
                    new_tag_id = original_tag_id + 1
                else:
                    new_tag_id = original_tag_id

        output.append(new_tag_id)

        prev_word = word_id

    return output


In [12]:
new_feature_names = dict(enumerate(feature_names))
new_feature_names[-100] = "SPECIAL"

In [13]:
new_labels = align_labels_with_split_tokens(tag_ids, inputs.word_ids())

new_tags = map(lambda tag_id: new_feature_names[tag_id], new_labels)

df(zip(inputs.tokens(), inputs.word_ids(), new_labels, new_tags))

0     1    2        3
0            [CLS]   NaN -100  SPECIAL
1          Germany   0.0    5    B-LOC
2                '   1.0    0        O
3                s   1.0    0        O
4   representative   2.0    0        O
5               to   3.0    0        O
6              the   4.0    0        O
7         European   5.0    3    B-ORG
8            Union   6.0    4    I-ORG
9                '   7.0    0        O
10               s   7.0    0        O
11      veterinary   8.0    0        O
12       committee   9.0    0        O
13          Werner  10.0    1    B-PER
14               Z  11.0    2    I-PER
15          ##wing  11.0    2    I-PER
16          ##mann  11.0    2    I-PER
17            said  12.0    0        O
18              on  13.0    0        O
19       Wednesday  14.0    0        O
20       consumers  15.0    0        O
21          should  16.0    0        O
22             buy  17.0    0        O
23           sheep  18.0    0        O
24            ##me  18.0    0        O
25            ##at  18.0    0        O
26            from  19.0    0        O
27       countries  20.0    0        O
28           other  21.0    0        O
29            than  22.0    0        O
30         Britain  23.0    5    B-LOC
31           until  24.0    0        O
32             the  25.0    0        O
33      scientific  26.0    0        O
34          advice  27.0    0        O
35             was  28.0    0        O
36         clearer  29.0    0        O
37               .  30.0    0        O
38           [SEP]   NaN -100  SPECIAL

### Apply to the entire dataset

In [14]:
# Peek at "tokens".
df(raw_datasets["train"]["tokens"])

0           1               2     3     4         5        6    \
0            EU     rejects          German  call    to   boycott  British   
1         Peter   Blackburn            None  None  None      None     None   
2      BRUSSELS  1996-08-22            None  None  None      None     None   
3           The    European      Commission  said    on  Thursday       it   
4       Germany          's  representative    to   the  European    Union   
...         ...         ...             ...   ...   ...       ...      ...   
14036        on      Friday               :  None  None      None     None   
14037  Division         two            None  None  None      None     None   
14038  Plymouth           2         Preston     1  None      None     None   
14039  Division       three            None  None  None      None     None   
14040   Swansea           1         Lincoln     2  None      None     None   

             7           8          9    ...   103   104   105   106   107  \
0           lamb           .       None  ...  None  None  None  None  None   
1           None        None       None  ...  None  None  None  None  None   
2           None        None       None  ...  None  None  None  None  None   
3      disagreed        with     German  ...  None  None  None  None  None   
4             's  veterinary  committee  ...  None  None  None  None  None   
...          ...         ...        ...  ...   ...   ...   ...   ...   ...   
14036       None        None       None  ...  None  None  None  None  None   
14037       None        None       None  ...  None  None  None  None  None   
14038       None        None       None  ...  None  None  None  None  None   
14039       None        None       None  ...  None  None  None  None  None   
14040       None        None       None  ...  None  None  None  None  None   

        108   109   110   111   112  
0      None  None  None  None  None  
1      None  None  None  None  None  
2      None  None  None  None  None  
3      None  None  None  None  None  
4      None  None  None  None  None  
...     ...   ...   ...   ...   ...  
14036  None  None  None  None  None  
14037  None  None  None  None  None  
14038  None  None  None  None  None  
14039  None  None  None  None  None  
14040  None  None  None  None  None  

[14041 rows x 113 columns]

In [15]:
def tokenize_and_align(examples):
    """
    Given a list of sentences 
    and a list of token ids, output a dataset of the tokenized
    features and the properly-aligned labels. 
    """

    list_of_sentences_of_tokens = examples["tokens"]
    list_of_sentences_of_tag_ids = examples["ner_tags"]

    tokenized_inputs = tokenizer(
        list_of_sentences_of_tokens, 
        truncation=True,  
        # Truncate to the maximum possible length of the model. 
        is_split_into_words=True
    )
    
    list_of_aligned_tags_ids = []

    for (sentence_index, tag_ids) in enumerate(list_of_sentences_of_tag_ids):
        token_ids = tokenized_inputs.word_ids(sentence_index)
        aligned_tag_ids = align_labels_with_split_tokens(tag_ids, token_ids)
        list_of_aligned_tags_ids.append(aligned_tag_ids)

    tokenized_inputs["labels"] = list_of_aligned_tags_ids
    return tokenized_inputs

In [16]:
tokenized_datasets = raw_datasets.map(
    tokenize_and_align,
    batched=True,
    remove_columns=raw_datasets["train"].column_names
)

Loading cached processed dataset at /root/.cache/huggingface/datasets/conll2003/conll2003/1.0.0/40e7cb6bcc374f7c349c83acd1e9352a4f09474eb691f64f364ee62eb65d0ca6/cache-3b2f5f9281210785.arrow
Loading cached processed dataset at /root/.cache/huggingface/datasets/conll2003/conll2003/1.0.0/40e7cb6bcc374f7c349c83acd1e9352a4f09474eb691f64f364ee62eb65d0ca6/cache-1a6416a06fcc9d44.arrow
Loading cached processed dataset at /root/.cache/huggingface/datasets/conll2003/conll2003/1.0.0/40e7cb6bcc374f7c349c83acd1e9352a4f09474eb691f64f364ee62eb65d0ca6/cache-712ad618bec2be3e.arrow


## Data Collation

In [17]:
from transformers import DataCollatorForTokenClassification

data_collator = DataCollatorForTokenClassification(tokenizer=tokenizer)
batch = data_collator([tokenized_datasets["train"][index] for index in range(2)])

for key, value in batch.items():
    print(key)
    print(value)
    print()

attention_mask
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])

input_ids
tensor([[  101,  7270, 22961,  1528,  1840,  1106, 21423,  1418,  2495, 12913,
           119,   102],
        [  101,  1943, 14428,   102,     0,     0,     0,     0,     0,     0,
             0,     0]])

labels
tensor([[-100,    3,    0,    7,    0,    0,    0,    7,    0,    0,    0, -100],
        [-100,    1,    2, -100, -100, -100, -100, -100, -100, -100, -100, -100]])

token_type_ids
tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])



In [18]:
from datasets import load_metric
metric = load_metric("seqeval")

In [19]:
labels = raw_datasets["train"][0]["ner_tags"]
labels
predictions = labels.copy()
predictions[2] = 0
predictions[6] = 0

labels = list(map(lambda tag_id:feature_names[tag_id], labels))
predictions = list(map(lambda tag_id:feature_names[tag_id], predictions))

In [20]:
df(zip(labels, predictions))

0      1
0   B-ORG  B-ORG
1       O      O
2  B-MISC      O
3       O      O
4       O      O
5       O      O
6  B-MISC      O
7       O      O
8       O      O

In [21]:
metric.compute(predictions=[predictions], references=[labels])

/opt/conda/lib/python3.7/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


{'MISC': {'precision': 0.0, 'recall': 0.0, 'f1': 0.0, 'number': 2},
 'ORG': {'precision': 1.0, 'recall': 1.0, 'f1': 1.0, 'number': 1},
 'overall_precision': 1.0,
 'overall_recall': 0.3333333333333333,
 'overall_f1': 0.5,
 'overall_accuracy': 0.7777777777777778}

In [67]:
id2label = {str(index): label for index, label in enumerate(label_names)}
label2id = {v: k for k, v in id2label.items()}

## Model

In [69]:
from transformers import AutoModelForTokenClassification

In [70]:
from torch.utils.data import DataLoader

train_dataloader = DataLoader(
    tokenized_datasets["train"],
    shuffle=True,
    collate_fn=data_collator,
    batch_size=32,
)

eval_dataloader = DataLoader(
    tokenized_datasets["validation"],
    collate_fn=data_collator,
    batch_size=32,
)

In [71]:
model = AutoModelForTokenClassification.from_pretrained(
    "bert-base-cased",
    id2label=id2label,
    label2id=label2id,
)

Some weights of the model checkpoint at bert-base-cased were not used when initializing BertForTokenClassification: ['cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForTokenClassification were not initialized from the model checkpoint at bert-base-cas

In [72]:
model.config.num_labels


9

In [73]:
from torch.optim import AdamW

optimizer = AdamW(model.parameters(), lr=2e-5)

In [74]:
from accelerate import Accelerator

accelerator = Accelerator()
model, optimizer, train_dataloader, eval_dataloader = accelerator.prepare(
    model, optimizer, train_dataloader, eval_dataloader
)

In [75]:
from transformers import get_scheduler

num_train_epochs = 10
num_update_steps_per_epoch = len(train_dataloader)
num_training_steps = num_train_epochs * num_update_steps_per_epoch
print(num_training_steps)

lr_scheduler = get_scheduler(
    "linear",
    optimizer=optimizer,
    num_warmup_steps=0,
    num_training_steps=num_training_steps,
)

4390


In [76]:
label_names = ner_feature.feature.names
label_names

['O', 'B-PER', 'I-PER', 'B-ORG', 'I-ORG', 'B-LOC', 'I-LOC', 'B-MISC', 'I-MISC']

In [80]:
def postprocess(predictions, labels):
    predictions = predictions.detach().cpu().clone().numpy()
    labels = labels.detach().cpu().clone().numpy()

    true_labels = [[id2label[str(l)] for l in label if l != -100] for label in labels]
    prediction_labels = [[id2label[str(l)] for l in label if l != -100] for label in predictions]
    # true_labels = []
    # prediction_labels = []
    # for label_id in label_ids:
    #     if label_id != 100:
    #         label = id2label[label_id]
    #         true_labels.append(label)

    # for label_id in predictions:
    #     if label_id != 100:
    #         label = id2label[label_id]
    #         prediction_labels.append(label)
    
    
    return true_labels, prediction_labels



In [81]:
from tqdm.auto import tqdm
import torch

progress_bar = tqdm(range(num_training_steps))


for epoch in range(num_train_epochs):
    model.train()
    for batch in train_dataloader:
        outputs = model(**batch)
        loss = outputs.loss
        accelerator.backward(loss)

        optimizer.step()
        lr_scheduler.step()
        optimizer.zero_grad()
        progress_bar.update(1)

    model.eval()

    for batch in eval_dataloader:
        with torch.no_grad():
            outputs = model(**batch)

        predictions = outputs.logits.argmax(dim=1)
        labels = batch["labels"]

        predictions = accelerator.pad_across_processes(predictions, dim=1, pad_index=-100)
        labels = accelerator.pad_across_processes(labels, dim=1, pad_index=-100)

        predictions_gathered = accelerator.gather(predictions)
        labels_gathered = accelerator.gather(labels)

        true_labels, prediction_labels = postprocess(predictions_gathered, labels_gathered)
        metric.add_batch(predictions=prediction_labels, reference=true_labels)

    results = metric.compute()
    print(
        f"Epoch {epoch}:", 
        {
            key: results[f"overall_{key}"]
            for key in ["precision", "recall", "f1", "accuracy"]
        },
    )


accelerator.wait_for_everyone()
unwrapped_model = accelerator.unwrap_model(model)

  0%|          | 0/4390 [00:00<?, ?it/s]

KeyError: '10'

In [ ]:
id2label


{0: 'O',
 1: 'B-PER',
 2: 'I-PER',
 3: 'B-ORG',
 4: 'I-ORG',
 5: 'B-LOC',
 6: 'I-LOC',
 7: 'B-MISC',
 8: 'I-MISC',
 -100: 'SPECIAL'}